### PR TITLE
compile locks with rebar3

### PR DESCRIPTION
**Pull request by benoitc**
allows to compile with rebar3. Please note I am for now using a fork of plain_fsm since the last one in hex.pm (1.4.0) introduces an issue when you try to launch more than once the common tests. I provided a PR for it:

https://github.com/uwiger/plain_fsm/pull/14

### CODE REVIEW

**Comment by benoitc** [comment]
I can make an update that link to anyway hex.pm release when you want :)

**Comment by uwiger** [comment]
Yes, if you could update it to use the 1.4.1 version of plain_fsm, that would be great.

**Comment by benoitc** [comment]
done :)

**Comment by uwiger** [comment]
Yes ..., though as long as the `Makefile` uses rebar 2 (not a requirement for my part), this change breaks `make`.

**Comment by uwiger** [comment]
Thanks.

**Pull request merged**
