### PR TITLE
changed nodes mgmt to ordset; added test cases

### PR DESCRIPTION
**Pull request by uwiger**
Trying to close in on reported netsplit issues in leader election. Ref #30

### CODE REVIEW

**Comment by benoitc** [comment]
what's the status of this PR?

**Comment by uwiger** [comment]
I think I forgot about it while waiting for feedback. :)

**Comment by benoitc** [comment]
:) looks ok there though I didn't do any extensive testing

**Comment by uwiger** [comment]
I tried running `make test` on my machine, but it failed in `ct_slave:spawn_remote_node()`. I think this is more related to my IP config than to the code. Annoying, though.

**Comment by uwiger** [comment]
Rebased and ran the test suite several times. Seems to work.

**Pull request merged**
